### ISSUE TITLE
Doesn't decode stack

### ISSUE THREAD

**Issue by technobilly** [yo2seol/P4-Wireshark-Dissector#16]
Hi, for fun I took a p4 program which contained the standard mpls_t from switch.p4 and renamed the header and fields like so:

header_type breakfast_t {
    fields {
        bacon : 20;
        eggs : 3;
        toast : 1;
        jam : 8;
    }
}

I then loaded the resulting lua into wireshark, read a pcap file containing 8 MPLS labels (I disabled MPLS decoding) and got the attached result. It only decodes the first label as a "breakfast." Is this a limitation in the dissector generator or a pilot error? Thanks.
![breakfast-lua](https://user-images.githubusercontent.com/24441724/27501625-560e6b6c-5823-11e7-8eed-66be8c511b8a.png)

**Comment by gnikol** [comment]
Hi,

Thanks for trying the software! I'm afraid that this is a current limitation of the generated dissectors, i.e. they do not support chaining/stacking, but it is definitely a feature on my radar!

Thanks
Yiorgos
